# Generated by Django 5.1.3 on 2024-12-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Загрузите фото книги')),
                ('description', models.TextField(blank=True, verbose_name='Укажите названия фильма')),
                ('price', models.FloatField(default=10, verbose_name='Укажите цену книги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('Ужасы', 'Ужасы'), ('Комедия', 'Комедия'), ('Приключения', 'Приключения'), ('Фантастика', 'Фантастика')], default='Фантастика', max_length=100)),
                ('gmail', models.CharField(default='Puskin1@gmail.com', max_length=100, verbose_name='укажите почту автора')),
                ('director', models.CharField(default='Пушкин', max_length=100, verbose_name='Укажите автора')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
