# Generated by Django 5.1.3 on 2024-12-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_blod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Укажите названия книги'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='укажите названия фильма'),
        ),
    ]
