# Generated by Django 5.1.3 on 2024-12-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_blod', '0003_bookmodel_image_alter_bookmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='films/', verbose_name='Загрузите фото фильма'),
        ),
    ]
