# Generated by Django 5.1.3 on 2024-12-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_blod', '0007_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
