# Generated by Django 5.1.3 on 2024-12-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('age_catherine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
