# Generated by Django 5.1.3 on 2024-12-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_catherine', '0002_remove_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
