# Generated by Django 5.1.3 on 2024-12-18 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0002_basketmodel_delete_basket'),
        ('library_blod', '0008_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='library_blod.bookmodel'),
        ),
    ]
